import type { Review } from './types'

/**
 * Avaliações de compras feitas na loja do vendedor na Shopee (confirmado pelo
 * vendedor em 26/09/2026). Texto copiado sem edição; nomes mascarados (o
 * repositório é público). A Shopee não passou as notas em estrelas: sem nota,
 * a avaliação aparece sem estrelas (nunca estimar). Duas avaliações só com
 * vídeo da camisa do Lula (67bdgb9gkx e deia12723) ficaram de fora por não terem texto;
 * na camisa Bolsonaro entraram todas, a pedido do vendedor.
 */
type Entrada = Omit<Review, 'productId' | 'modelId' | 'verified' | 'origin'>
const daShopee = (productId: Review['productId'], modelId: string) => (r: Entrada): Review => ({
  productId,
  modelId,
  verified: true,
  origin: 'Shopee',
  ...r,
})
const camisaLula = daShopee('13', 'camisa')
const camisaBolsonaro = daShopee('22', 'camisa')
const boneBandeira = daShopee('22', 'nome-bandeira')
const boneFlavio = daShopee('22', 'flavio')
const boneCamuflado = daShopee('22', 'camuflado')
const boneNumero13 = daShopee('13', 'numero-13')
const boneLulaEstrela = daShopee('13', 'nome-lula-estrela')
const boneLulaLetras = daShopee('13', 'nome-lula-letras')

/** Seis avaliações enviadas para o Boné Lula (letras grandes); também aparecem no Boné Simples. */
const lulaSeis: Entrada[] = [
  {
    author: 'a*****e',
    date: '2026-09-04',
    variantLabel: 'Branco',
    text: 'Eu tinha um vermelho que comprei em outro canto, ai comprei o branco aqui, o material é bom sem cheiro vale cada centavos.',
  },
  {
    author: 'y*****f',
    date: '2026-08-27',
    variantLabel: 'Vermelho',
    details: [
      ['Visual sugerido', 'eleicao'],
      ['Adequado', 'dia da eleicao'],
      ['Custo-benefício', 'otimo'],
    ],
    text: 'Boné maravilhoso é Lula de novo meu povo 🥰🥰',
    helpful: 22,
  },
  {
    author: 'g*****a',
    date: '2026-09-04',
    variantLabel: 'Branco',
    details: [
      ['Ocasião adequada', 'perfeito para as eleições'],
      ['Visual sugerido', 'pedi branco combina com tudo'],
      ['Estilo', 'lindo demais'],
    ],
    helpful: 2,
  },
  {
    author: 'a*****8',
    date: '2026-09-06',
    variantLabel: 'Vermelho',
    details: [
      ['Estilo', 'top'],
      ['Custo-benefício', 'ótimo'],
    ],
    text: 'Gostei muito rumo ao tetra!!!',
    helpful: 1,
  },
  {
    author: 'l*****4',
    date: '2026-09-22',
    variantLabel: 'Vermelho',
    details: [['Conforto', 'chegou dentro do prazo e o material de boa qualidade....']],
  },
  {
    author: 'i*****a',
    date: '2026-09-21',
    variantLabel: 'Vermelho',
    details: [
      ['Conforto', 'o boné é confortável porém veio com um defeito na letra no segundo L'],
      ['Qualidade', 'boa'],
      ['Estilo', 'casual'],
    ],
  },
]

/** Avaliações que estavam no Trucker liso; o vendedor pediu para mostrá-las no Boné Simples. */
const exTruckerLiso: Entrada[] = [
  {
    author: 's*****1',
    date: '2026-09-17',
    variantLabel: 'Vermelho',
    text: 'É bom, mais achei que a qualidade fosse melhor, achei a frente muito pontuda',
  },
  {
    author: 'v*****0',
    date: '2026-09-11',
    variantLabel: 'Vermelho',
    text: 'Chegou rápido, igual ao anúncio...obrigada ao vendedor',
    helpful: 1,
  },
  {
    author: 'p*****3',
    date: '2026-09-26',
    variantLabel: 'Vermelho',
    details: [
      ['Qualidade', 'Boa'],
      ['Conforto', 'Ótimo'],
      ['Visual', 'Moderno…'],
    ],
  },
  { author: 'i*****s', date: '2026-09-25', variantLabel: 'Vermelho' },
  { author: 'h*****o', date: '2026-09-16', variantLabel: 'Vermelho', text: 'Ótima qualidade, recomendo!' },
  {
    author: 'g*****2',
    date: '2026-09-22',
    variantLabel: 'Vermelho',
    details: [['Conforto', 'achei de boa qualidade perfeito']],
  },
]

/**
 * Boné Simples: o vendedor pediu as mesmas avaliações nos dois "Boné Simples"
 * (vermelho, lado 13, e azul/verde, lado 22). Enviadas em 26/09/2026.
 */
const boneSimples: Entrada[] = [
  {
    author: 't*****7',
    date: '2024-11-25',
    photo: '/avaliacoes/bone-simples-1.png',
    variantLabel: 'Preto',
    details: [
      ['Parecido com anúncio', 'sim'],
      ['Qualidade', 'boa'],
    ],
    text: 'Acabou de chegar veio bem rápido ele é lindo é a cor que eu escolhi é só não é a parte de dentro durinha né para que ele fique bem durinho mas nada que perca o charme do boné a loja tá de parabéns pelo envio bem rápido mesmo',
    helpful: 125,
  },
  {
    author: 'm*****a',
    date: '2025-04-03',
    photo: '/avaliacoes/bone-simples-2.webp',
    variantLabel: 'Preto',
    details: [
      ['Custo-benefício', 'otimo custo benefício'],
      ['Adequado', 'muito parecido com anuncio'],
      ['Visual sugerido', 'amei as cores e veste bem na cabeça'],
    ],
    text: 'Chegou super rápido 💨',
    helpful: 106,
  },
  {
    author: 'c*****4',
    date: '2024-12-03',
    photo: '/avaliacoes/bone-simples-3.webp',
    variantLabel: 'Verde Médio',
    details: [
      ['Parecido com anúncio', 'sim'],
      ['Qualidade', 'ótima'],
    ],
    text: 'Envio muito rápido, ótima qualidade e a cor é linda\nAmei já quero comprar outras cores',
    helpful: 26,
  },
  {
    author: 's*****m',
    date: '2025-08-04',
    variantLabel: 'Azul Escuro',
    text: 'Excelente boné, muito bem.feito e material.de qualidade. O feixe de regulagem é de fivela, muito bom, só jeito que que queria.\nO tecido dele é bem grosso, de ótima qualidade.',
    helpful: 12,
  },
  {
    author: 'l*****c',
    date: '2025-07-21',
    variantLabel: 'Bege Medio',
    text: 'Entrega foi super rápida! Muito bom o boné, bem acabado e serviu muito bem',
    helpful: 46,
  },
  {
    author: 'a*****6',
    date: '2025-06-23',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Custo-benefício', 'otimo'],
      ['Visual sugerido', 'lindo'],
      ['Adequado', 'sim'],
    ],
    text: 'Produto lindo e de boa qualidade',
  },
  {
    author: 'a*****2',
    date: '2024-12-27',
    variantLabel: 'Preto',
    text: 'Chegou rápido e é ótimo pelo valor! Podem comprar sem medo',
    helpful: 27,
  },
  {
    author: 'y*****n',
    date: '2026-05-14',
    variantLabel: 'Bege Medio',
    details: [
      ['Conforto', 'bom'],
      ['Qualidade', 'tecido muito bom'],
    ],
    text: 'Gostei muito da qualidade do produto, ajuste na cabeça muito bom',
    helpful: 5,
  },
  {
    author: 'r*****1',
    date: '2024-12-04',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Parecido com anúncio', 'sim'],
      ['Qualidade', 'bom'],
    ],
    text: 'Gostei! Chegou certinho, conforme o que está na descrição.',
    helpful: 27,
  },
  {
    author: 'j*****5',
    date: '2026-05-22',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Conforto', 'achei muito confortável gostei muito'],
      ['Qualidade', 'qualidade muito boa gostei muito do tecido'],
    ],
    text: 'Resumindo o bone e muito bom pode comprar sem medo 👍',
    helpful: 2,
  },
  {
    author: 's*****a',
    date: '2026-05-02',
    variantLabel: 'Bege Medio',
    details: [['Conforto', 'lindo, veste bem e ainda vem com proteção por dentro pra não amassar. Amei']],
    text: 'Chegou super rápido, enviaram no mesmo dia da compra, muito obrigada 😍',
    helpful: 3,
  },
  {
    author: 'l*****t',
    date: '2026-02-07',
    variantLabel: 'Cinza Claro',
    details: [
      ['Adequado', 'perfeito'],
      ['Ocasião adequada', 'comprei p personaizar'],
      ['Estilo', 'bone estilo baseball'],
    ],
    text: 'Tamanho perfeito, mais feminino e delicado. Esperando mais cores p comprar',
    helpful: 2,
  },
  {
    author: 'm*****6',
    date: '2026-06-11',
    variantLabel: 'Bege Medio',
    text: 'Lindos e de ótima qualidade, sem falar no preço convidativo. Gostei!',
    helpful: 2,
  },
  {
    author: 'c*****1',
    date: '2026-04-09',
    variantLabel: 'Azul Escuro',
    details: [
      ['Conforto', 'tecido fresco sensacional'],
      ['Qualidade', 'muito bom ,acabamento perfeito,leve,não esquenta a cabeça'],
    ],
    text: 'Mais no insta claudiocostaof',
    helpful: 16,
  },
  {
    author: 'g*****a',
    date: '2026-07-14',
    variantLabel: 'Bege Medio',
    details: [
      ['Conforto', 'confortável'],
      ['Qualidade', 'material bom'],
    ],
    text: 'Gostei bastante, primeiro comprei 1 marrom e depois comprei o bege',
    helpful: 1,
  },
  {
    author: 'r*****a',
    date: '2026-05-17',
    variantLabel: 'Azul Médio',
    text: 'Chegou no prazo e bem embalado, o boné é de qualidade e o seu acampamento é excelente. Gostei bastante, comprarei mais. Top !!!',
    helpful: 3,
  },
  {
    author: 'g*****e',
    date: '2026-06-06',
    variantLabel: 'Bege Medio',
    details: [
      ['Conforto', 'É confortável e eu nem era de usar boné'],
      ['Qualidade', 'Muito boa, custo benefício muito bom.'],
    ],
    text: 'Compraria novamente.',
  },
  {
    author: 'g*****0',
    date: '2026-05-28',
    variantLabel: 'Preto',
    text: 'Perfeito e muito lindo! Tamanho ideal e super confortável. Material de muita qualidade. Recomendo!!',
    helpful: 1,
  },
  {
    author: 'd*****1',
    date: '2026-07-02',
    variantLabel: 'Amarelo',
    details: [['Qualidade', 'excelente']],
    text: 'Meu boné chegou,já é o segundo que compro, muito bom.',
  },
  {
    author: '0*****2',
    date: '2026-05-24',
    variantLabel: 'Bege Medio',
    details: [
      ['Conforto', 'bem confortável e ajustável.'],
      ['Qualidade', 'surpreendente de boa, bem acabado as costuras e corte. material bom.'],
    ],
    text: 'Chegou tudo certo, é bonito e confortável.\nNunca fui de usar boné, estou tentando me acostumar kkkk.',
    helpful: 2,
  },
  {
    author: 'a*****i',
    date: '2026-07-04',
    variantLabel: 'Bege Medio',
    text: 'Chegou antes da data prevista e tudo certo conforme o anunciado pelo vendedor. Gostei muito da compra e recomendo a loja.',
  },
  {
    author: 'b*****p',
    date: '2026-06-22',
    variantLabel: 'Bege Medio',
    details: [
      ['Conforto', 'bem confortável, fica bem na cabeça'],
      ['Qualidade', 'excelente acabamento, melhor do que eu esperava'],
    ],
  },
  {
    author: 'p*****e',
    date: '2026-05-01',
    variantLabel: 'Verde Médio',
    text: 'Perfeito! A cor maravilhosa e muito bem feito. Vou pegar outras cores',
    helpful: 2,
  },
  {
    author: 'g*****2',
    date: '2026-03-30',
    variantLabel: 'Bege Medio',
    details: [['Estilo', 'É um boné. Não é ciência de foguetes.']],
    text: 'Chegou bem embalado e rápido. É confortável ao uso e parece ser bem costurado. A cor tbm é igual ao anunciado. Bom tbm por ficar acima da linha da orelha. Recomendo e vou comprar novamente.',
    helpful: 6,
  },
  {
    author: 'j*****1',
    date: '2026-05-18',
    variantLabel: 'Preto',
    details: [
      ['Conforto', 'não causa desconforto'],
      ['Qualidade', 'o tecido e grosso, e bem preto'],
    ],
    text: 'Não entendo de boné, comprei para presentear, porém achei muito bonito e bem escuro e parece de boa qualidade',
    helpful: 1,
  },
  {
    author: 'l*****l',
    date: '2025-04-01',
    variantLabel: 'Bege Medio',
    text: 'Bom custo benefício. Essa cor tá mais pra um nude rosado',
    helpful: 19,
  },
  {
    author: 'f*****o',
    date: '2026-08-02',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Conforto', 'o boné é confortável e ajustável'],
      ['Qualidade', 'de excelência qualidade'],
      ['Estilo', 'estiloso'],
    ],
    text: 'O boné é de excelência qualidade material confortável',
  },
  {
    author: 'c*****2',
    date: '2026-08-24',
    variantLabel: 'Verde Médio',
    text: 'Amei e igual a foto.\nQuero outras cores.\nChegou rápido',
  },
  {
    author: 'a*****_',
    date: '2025-03-14',
    variantLabel: 'Cinza Escuro',
    details: [['Custo-benefício', 'Excelente!']],
    text: 'Qualidade impecável, chegou rápido e o material é ótimo, a cor linda! Vale muito a pena, comprem sem medo.',
    helpful: 10,
  },
  {
    author: 'g*****r',
    date: '2024-11-30',
    variantLabel: 'Azul Escuro',
    details: [
      ['Parecido com anúncio', 'sim'],
      ['Qualidade', 'boa'],
    ],
    text: 'Chegou rápido, sem defeitos. Veste bem.',
    helpful: 29,
  },
  {
    author: 'r*****7',
    date: '2025-04-24',
    variantLabel: 'Cinza Escuro',
    text: 'Chegou rápido, o boné encaixa bem na cabeça, bem costurado, comprarei mais',
    helpful: 4,
  },
  {
    author: 'p*****e',
    date: '2025-05-08',
    variantLabel: 'Azul Escuro',
    details: [
      ['Adequado', 'Muito bonito o boné, confortável de usar! Gostei muito!'],
      ['Estilo', 'Bonito, aba arredondada! Estilo basebol ⚾️'],
      ['Custo-benefício', 'preço bom. Vale o investimento! Em breve comprarei outras cores. Optei pelo azul marinho!'],
    ],
    helpful: 7,
  },
  {
    author: 'c*****t',
    date: '2026-06-04',
    variantLabel: 'Bege Medio',
    text: 'Ótimo boné! O tecido é grosso, as costuras são bem feitas e a qualidade geral é muito boa. Gostei especialmente do fato de a parte da frente não ser estruturada (apenas a aba), exatamente como eu procurava, pois dá um caimento mais natural. Outro ponto positivo foi a entrega: comprei em um dia e o produto chegou no dia seguinte. Recomendo!',
    helpful: 4,
  },
  {
    author: '_*****3',
    date: '2025-03-20',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Adequado', 'sim'],
      ['Ocasião adequada', 'sim'],
      ['Custo-benefício', 'ótimo'],
    ],
    text: 'Ótimo qualidade e entrega super rápida.',
    helpful: 8,
  },
  {
    author: 'a*****o',
    date: '2025-04-09',
    variantLabel: 'Branco',
    text: 'Formato de cabeça bom , boné bem grande , com ajuste perfeito . Estilo beisebol , branco e limpo .\nEmbalado com cuidado , preservando a qualidade do produto.',
    helpful: 9,
  },
  {
    author: 'm*****o',
    date: '2025-06-07',
    variantLabel: 'Preto',
    text: 'Muito bom, veste muito bem, a entrega foi rápida e muito bem embalada. Esse já é o segundo que eu compro.',
    helpful: 2,
  },
  {
    author: 'n*****_',
    date: '2026-05-11',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Conforto', 'confortavel'],
      ['Qualidade', 'qualidade boa veio conforme o anuncio. entrega rapida. gostei'],
    ],
    helpful: 1,
  },
  {
    author: 'e*****a',
    date: '2026-04-01',
    variantLabel: 'Branco',
    text: 'Pelo preço valeu super a pena a qualidade é ótima valeu super a pena 🫶',
    helpful: 1,
  },
  {
    author: 's*****o',
    date: '2025-11-14',
    variantLabel: 'Cinza Escuro',
    details: [
      ['Estilo', 'casual'],
      ['Visual sugerido', 'qualquer'],
    ],
    text: 'Comprei a cor cinza escuro. O tecido é grossinho e tem um regulador que guarda o excesso dentro.',
    helpful: 2,
  },
  {
    author: 'm*****9',
    date: '2026-05-09',
    variantLabel: 'Preto',
    text: 'Entrega rápida e embalado normalmente porém chegou tudo certinho e sem nenhum detalhe. Será um presente mas gostei bastante da qualidade do tecido e da confecção, muito bem construído, valeu a pena. Indico a loja e o produto.',
  },
  {
    author: 'l*****7',
    date: '2026-05-11',
    variantLabel: 'Azul Escuro',
    text: 'Chegou dentro do prazo de entrega, tudo ok. Comprei para meu esposo e ele gostou bastante. Parece bom.',
    helpful: 1,
  },
  {
    author: 'v*****i',
    date: '2026-03-21',
    variantLabel: 'Bege Medio',
    details: [
      ['Qualidade', 'Bonissima pro preço'],
      ['Estilo', 'todos!'],
      ['Conforto', 'ótimo'],
    ],
    text: 'Eu gastava muito pra encontrar um boné que eu goste pelo formato da minha cabeça, esses me atenderam maravilhosamente bem, não dá aspecto da "cabeça chupada", são bem estruturados, caimento perfeito, custo benefício absurdo!!! Comprei os esportivos e os de tecido, ambos ótimos!',
    helpful: 4,
  },
]

const obrigada = 'Obrigada pela compra, Deus abençoe. Estamos à disposição'
const obrigada2 = 'Obrigada pela compra. Deus abençoe\nEstamos à disposição'

export const reviews: Review[] = [
  camisaLula({
    author: 't*****e',
    date: '2026-09-08',
    photo: '/avaliacoes/camisa-lula-1.webp',
    variantLabel: 'Vermelho, M',
    details: [
      ['Conforto', 'Camiseta confortável'],
      ['Qualidade', 'Ótima qualidade'],
      ['Modelagem', 'Modelagem perfeita'],
    ],
    text: 'Comprem, não vão se arrepender 😉',
    helpful: 30,
  }),
  camisaLula({
    author: '7*****q',
    date: '2026-09-02',
    photo: '/avaliacoes/camisa-lula-2.webp',
    variantLabel: 'Marrom, G1',
    details: [
      ['Conforto', 'bom confortavel'],
      ['Visual sugerido', 'basico'],
      ['Estilo', 'Lula na veia'],
    ],
    text: 'Bom\nMaterial bom e linda a camisa 👚 quero comprar uma de cada cor',
    helpful: 15,
  }),
  camisaLula({
    author: 'h*****k',
    date: '2026-08-26',
    photo: '/avaliacoes/camisa-lula-3.webp',
    variantLabel: 'Marrom, GG',
    details: [
      ['Qualidade', 'ótimo leve'],
      ['Ocasião adequada', 'festa política'],
      ['Visual sugerido', 'amei bem confortável do jeito do anúncio'],
    ],
    text: 'Comprei o tamanho que uso e deu certo',
    helpful: 10,
  }),
  camisaLula({
    author: 's*****n',
    date: '2026-09-10',
    photo: '/avaliacoes/camisa-lula-4.webp',
    variantLabel: 'Vermelho, G',
    details: [
      ['Conforto', 'a camisa é ótima'],
      ['Qualidade', 'a qualidade pelo valor é boa'],
      ['Modelagem', 'o tamanho g deu certinho eu peso 79kg e ficou super confortavel'],
    ],
    helpful: 2,
  }),
  camisaLula({
    author: 'k*****0',
    date: '2026-09-10',
    photo: '/avaliacoes/camisa-lula-5.webp',
    variantLabel: 'Vermelho, M',
    details: [
      ['Conforto', 'pano maravilhoso'],
      ['Qualidade', 'boa'],
      ['Modelagem', 'perfeito'],
    ],
    helpful: 9,
  }),
  camisaLula({
    author: 'm*****1',
    date: '2026-09-01',
    variantLabel: 'Vermelho, M',
    details: [
      ['Qualidade', 'A qualidade é muito boa, pode comprar sem medo'],
      ['Conforto', 'Muito confortavel'],
      ['Custo-benefício', 'Magnifico'],
    ],
    helpful: 1,
  }),
  camisaLula({
    author: 'p*****a',
    date: '2026-08-10',
    variantLabel: 'Vermelho, G',
    text:
      'Uma das blusas veio correta!\nA que era tamanho pp, arrancaram a etiqueta e mandaram uma bem maior!\nVocês pensam que o consumidor é burro!\nMais honesto seria admitir o erro!',
    sellerReply:
      'Bom dia, se uma das blusas foi correta maravilha. O seu pedido foi de justamente UMA blusa, a outra foi cortesia! Se eu soubesse que geraria esse descontentamento e a má avaliação, eu teria enviado apenas UMA que foi a que você pagou. De qualquer forma, obrigado pela compra e desculpa ter enviado um brinde que não foi do seu agrado.',
    helpful: 9,
  }),
  camisaLula({
    author: 't*****3',
    date: '2026-08-25',
    variantLabel: 'Marrom, GG',
    details: [['Conforto', 'bom']],
  }),
  camisaLula({
    author: 'l*****2',
    date: '2026-08-21',
    variantLabel: 'Cinza, G1',
    details: [['Produto', 'Baixa qualidade']],
    text: 'Comprei no tamanho g1 para mim...tive que dar pro meu filho que usa p e quase ficou pequeno.',
    helpful: 4,
  }),
  camisaLula({
    author: 'r*****2',
    date: '2026-09-12',
    variantLabel: 'Vermelho, G1',
    details: [['Conforto', 'gostei bastante']],
  }),
  camisaLula({
    author: 'd*****r',
    date: '2026-09-05',
    variantLabel: 'Vermelho, G1',
    text: 'Top',
  }),
  camisaLula({
    author: 'a*****7',
    date: '2026-09-23',
    variantLabel: 'Vermelho, M',
    details: [
      ['Conforto', 'pano leve e fino.'],
      ['Qualidade', 'Bom.'],
      ['Modelagem', 'Excelente.'],
    ],
    text:
      'A camiseta chegou no prazo estimado, com boa condição de uso e de material bom. Vestiu bem e tem tamanho relativamente perfeito às medidas do meu corpo. Satisfeito com o pedido, super indico à loja! Satisfação imensa!! 🙌🏻🤝',
    helpful: 1,
  }),
  camisaLula({
    author: 'a*****1',
    date: '2026-09-19',
    variantLabel: 'Branco, P',
    details: [
      ['Conforto', 'levinho e macio'],
      ['Qualidade', 'costura bem feita'],
      ['Modelagem', 'veste muito bem'],
    ],
    text: 'A camisa é linda, boa impressão, costura bem feita e entrega rápida! Amei, recomendo demais!\nÉ Lula é tetraaaaaaa! ❤️⭐️🇧🇷',
    helpful: 7,
  }),
  camisaLula({
    author: '_*****_',
    date: '2026-09-18',
    variantLabel: 'Vermelho, M',
    details: [
      ['Conforto', 'Confortável'],
      ['Qualidade', 'Não é absurda, é ok pelo preço'],
      [
        'Modelagem',
        'Por ser masculina, pensei que ficaria maior (peguei M), mas gostei do caimento, se pegasse P (pensando que seria maior por ser masculina) ficaria muito justa',
      ],
    ],
    helpful: 3,
  }),
  camisaLula({
    author: 'k*****8',
    date: '2026-09-26',
    variantLabel: 'Preto, GG',
    details: [
      ['Conforto', 'malha de boa qualidade, muito confortável'],
      ['Qualidade', 'ótima qualidade do tecido e estampa'],
      ['Modelagem', 'comprei GG uso 44, 46 ficou certinha. Depende gosto da pessoa, ficou certinha nem folga nem apertada'],
    ],
  }),
  camisaLula({
    author: 'm*****5',
    date: '2026-09-19',
    variantLabel: 'Vermelho, M',
    details: [
      ['Conforto', 'otimo'],
      ['Qualidade', 'super boa'],
    ],
    text: 'Super lindo eu amei e veio de um ótimo tamanho 😊 vou comprar mais vezes',
    helpful: 5,
  }),
  camisaLula({
    author: 'j*****t',
    date: '2026-09-24',
    variantLabel: 'Vermelho, PP',
    details: [
      ['Conforto', 'macia.'],
      ['Qualidade', 'malha excelente'],
      ['Modelagem', 'perfeita'],
    ],
    text:
      'Estou muitíssimo satisfeita. Só nesta loja encontrei o meu tamanho (pp). Preço justo! A malha e a estampa são de ótima qualidade. Recomendo. E agradeço aos vendedores/as e entregadores/as.',
  }),
  camisaLula({
    author: 'b*****l',
    date: '2026-09-26',
    variantLabel: 'Vermelho, M',
    details: [
      ['Conforto', 'super confortável'],
      ['Qualidade', 'qualidade ótima, estampa perfeita e a cor vermelha lindíssima'],
      ['Modelagem', 'eu pedi tamanho M e coube perfeitamente em mim'],
    ],
  }),
  camisaLula({
    author: 'i*****e',
    date: '2026-09-22',
    variantLabel: 'Vermelho, P',
    text: 'Eu amei, material bom, chegou rápido, estampa muito boa! BORA LULA!!!! ⭐️❤️',
    helpful: 6,
  }),
  camisaLula({
    author: 'm*****1',
    date: '2026-09-19',
    variantLabel: 'Vermelho, G',
    details: [
      ['Conforto', 'tecido macio'],
      ['Qualidade', 'de ótima qualidade'],
      ['Modelagem', 'bom caimento'],
    ],
  }),
  camisaLula({
    author: 'b*****2',
    date: '2026-09-22',
    variantLabel: 'Vermelho, G1 e Vermelho, P',
    details: [
      ['Conforto', 'muito confortável'],
      ['Qualidade', 'material otimo'],
      ['Modelagem', 'boa'],
    ],
    helpful: 3,
  }),
  camisaLula({
    author: 'm*****x',
    date: '2026-09-26',
    variantLabel: 'Vermelho, GG',
    details: [
      ['Conforto', 'a camisa tem um tecido bom'],
      ['Qualidade', 'a qualidade é boa'],
      ['Modelagem', 'venho do tamanho certo'],
    ],
  }),

  // Camisa Bolsonaro 22 (enviadas pelo vendedor em 26/09/2026)
  camisaBolsonaro({
    author: 'c*****r',
    date: '2026-09-25',
    variantLabel: 'Preto, G',
    photo: '/avaliacoes/camisa-bolsonaro-1.webp',
    text: 'A camisa é linda 😍 tecido ótimo!👏🏻👏🏻✌🏻 Flávio Bolsonaro 22.',
  }),
  camisaBolsonaro({
    author: 'c*****r',
    date: '2026-09-25',
    variantLabel: 'Preto, P',
    photo: '/avaliacoes/camisa-bolsonaro-2.webp',
    text: 'Camisa linda! O tecido é ótimo! Flávio Bolsonaro 22 ✌🏻',
  }),
  camisaBolsonaro({
    author: 'j*****2',
    date: '2026-09-23',
    variantLabel: 'Branco, GG',
    photo: '/avaliacoes/camisa-bolsonaro-3.webp',
    text: 'Veio com tamanho muito pequeno\nPedi um GG veio parecendo um M\nNão compre e meu aviso',
  }),
  camisaBolsonaro({
    author: 'i*****a',
    date: '2026-09-15',
    variantLabel: 'Preto, G e Preto, P',
    text: 'Amei a blusa, tamanhos bons, comprei 2 G e 2 P, a P achei até um pouco grande, mas tá perfeita!\nO tecido é de qualidade, bem grossinho.',
    sellerReply: obrigada,
    helpful: 1,
  }),
  camisaBolsonaro({
    author: 'c*****1',
    date: '2025-09-11',
    variantLabel: 'Preto, GG',
    details: [['Conforto', 'chegou muito rápido custo benefício muito bom adorei 👏👏👏']],
    sellerReply: obrigada2,
    helpful: 2,
  }),
  camisaBolsonaro({ author: 'y*****4', date: '2026-09-23', variantLabel: 'Preto, G', helpful: 1 }),
  camisaBolsonaro({ author: 'd*****5', date: '2026-09-20', variantLabel: 'Preto, G2', sellerReply: obrigada }),
  camisaBolsonaro({ author: 'e*****7', date: '2026-08-27', variantLabel: 'Preto, G1', sellerReply: obrigada }),
  camisaBolsonaro({ author: 'r*****r', date: '2025-09-23', variantLabel: 'Preto, M', sellerReply: obrigada2 }),
  camisaBolsonaro({ author: 'r*****9', date: '2026-01-11', variantLabel: 'Preto, P', sellerReply: obrigada2 }),
  camisaBolsonaro({ author: 'm*****a', date: '2026-08-11', variantLabel: 'Preto, G4', sellerReply: obrigada }),
  camisaBolsonaro({ author: 'v*****l', date: '2026-08-20', variantLabel: 'Preto, G4', sellerReply: 'Obrigada pela compra, Deus abençoe, estamos à disposição' }),
  camisaBolsonaro({ author: 'd*****0', date: '2026-09-13', variantLabel: 'Branco, G3', sellerReply: 'Obrigada pela compra, Deus abençoe.\nEstamos à disposição' }),
  camisaBolsonaro({ author: 'm*****u', date: '2026-09-13', variantLabel: 'Preto, M e Preto, G', sellerReply: 'Obrigada pela compra, Deus abençoe, estamos à disposição' }),
  camisaBolsonaro({ author: 't*****l', date: '2026-09-20', variantLabel: 'Preto, G', sellerReply: obrigada }),
  camisaBolsonaro({ author: 'j*****8', date: '2026-09-22', variantLabel: 'Preto, G3' }),
  camisaBolsonaro({ author: 'i*****s', date: '2026-09-22', variantLabel: 'Preto, GG' }),
  camisaBolsonaro({ author: 'g*****u', date: '2026-09-25', variantLabel: 'Preto, M' }),

  // Boné Brasil e bandeira (enviadas pelo vendedor em 26/09/2026)
  boneBandeira({
    author: '_*****s',
    date: '2026-06-20',
    photo: '/avaliacoes/bone-brasil-1.webp',
    variantLabel: 'Amarelo',
    text: 'Material excelente e qualidade impecável! Muiito bem bordado! Amei a cor, bem viva!! Comprarei mais cores com certeza!!!!',
    helpful: 7,
  }),
  boneBandeira({
    author: 'c*****a',
    date: '2026-07-04',
    photo: '/avaliacoes/bone-brasil-2.png',
    variantLabel: 'Amarelo',
    details: [
      ['Conforto', 'leve , confortável , ajustável perfeito'],
      ['Material', 'bem acabado , igual ao anúncio'],
      ['Estilo', 'bem moderno desbojado! Adorei 🥰'],
    ],
    helpful: 1,
  }),
  boneBandeira({
    author: 'a*****3',
    date: '2026-07-04',
    photo: '/avaliacoes/bone-brasil-3.webp',
    variantLabel: 'Azul',
    details: [
      ['Ocasião adequada', 'boné'],
      ['Estilo', 'ok'],
      ['Custo-benefício', 'bom custo benefício'],
    ],
    text: 'Boa qualidade e custo beneficio',
    helpful: 1,
  }),
  boneBandeira({
    author: 'b*****5',
    date: '2026-08-29',
    variantLabel: 'Azul',
    details: [
      ['Conforto', 'confortável'],
      ['Material', 'bom'],
      ['Estilo', 'casual'],
    ],
    text: 'Chegou rápido. Boa qualidade. Atende a necessidade',
  }),
  boneBandeira({
    author: 'f*****s',
    date: '2026-07-12',
    variantLabel: 'Preto',
    text: 'Chegou tudo certo e entregue antes do prazo final, muito bom o produto, vendedor recomendado.',
    helpful: 1,
  }),
  boneBandeira({
    author: 'o*****4',
    date: '2026-07-01',
    variantLabel: 'Amarelo',
    details: [
      ['Conforto', 'Achei o boné leve.'],
      ['Material', 'O material é muito bom.'],
      ['Estilo', 'O estilo é como eu queria para assistir o jogo do Brasil.'],
    ],
    text: 'Meu boné é bem leve e confortável, gostei bastante.Obrigada Chopee.',
    helpful: 3,
  }),
  boneBandeira({
    author: 'm*****2',
    date: '2026-06-09',
    variantLabel: 'Preto',
    details: [
      ['Ocasião adequada', 'casual, esportivo'],
      ['Visual sugerido', 'Otimo para esportes Brasileiros'],
    ],
    text: 'O boné lindo, cores vivas , bordado . Excelente matéria e bem acabado . Adorei',
    helpful: 6,
  }),
  boneBandeira({
    author: 'r*****1',
    date: '2026-07-11',
    variantLabel: 'Azul',
    details: [
      ['Conforto', 'achei lindo e confortável'],
      ['Estilo', 'gostei da cor do mesmo jeito da foto'],
      ['Material', 'o material e resistente é ótimo para o dia dia'],
    ],
  }),
  boneBandeira({
    author: 'f*****a',
    date: '2026-06-12',
    variantLabel: 'Preto',
    text: 'Gostamos boné ótimo material de excelência ao nome brasil bordado, chegou dentro do prazo',
    helpful: 1,
  }),
  boneBandeira({
    author: 's*****5',
    date: '2026-07-04',
    variantLabel: 'Amarelo',
    details: [
      ['Conforto', 'Confortável'],
      ['Material', 'Material bom'],
      ['Estilo', 'Estiloso'],
    ],
    text: 'Comprei para minha filha. Ela estava ansiosa. Chegou bem rápido.',
  }),
  boneBandeira({
    author: 'b*****i',
    date: '2026-06-13',
    variantLabel: 'Branco',
    text: 'Amei. Já usamos no primeiro jogo do Brasil. Chegou antes do previsto',
    helpful: 4,
  }),
  boneBandeira({
    author: 'z*****9',
    date: '2026-06-18',
    variantLabel: 'Azul',
    text: 'Gostei produto de boa qualidade ótimo acabamento chegou antes do prazo parabéns',
  }),
  boneBandeira({
    author: 'r*****q',
    date: '2026-07-05',
    variantLabel: 'Verde',
    details: [
      ['Conforto', 'Bom'],
      ['Material', 'Ótimo'],
      ['Estilo', 'Super satisfeita'],
    ],
    text: 'Comprei para o meu marido\nEle gostou muito',
  }),
  boneBandeira({
    author: 'r*****2',
    date: '2026-06-22',
    variantLabel: 'Amarelo',
    details: [
      ['Conforto', 'confortável'],
      ['Estilo', 'gostei da cor muito bonito o bordado muito bem feito'],
    ],
  }),
  boneBandeira({
    author: 'w*****t',
    date: '2026-06-26',
    variantLabel: 'Amarelo',
    text: 'Lindo e de ótima qualidade. Cor viva e bordado bem feito.',
  }),
  boneBandeira({
    author: 'v*****1',
    date: '2026-06-23',
    variantLabel: 'Preto',
    details: [
      ['Conforto', 'O boné é lindo !!excelente material ,os bordados sao super bem feitos e a modelagem dele é perfeita .'],
    ],
  }),
  boneBandeira({
    author: 'm*****x',
    date: '2026-06-15',
    variantLabel: 'Verde, Preto, Azul',
    text: 'São bacanas. Cores vivas. Não me dei conta na hora da compra que o verde era um pouco mais caro. O tecido dele é mais grosso que dos outros.',
  }),
  boneBandeira({
    author: 'j*****i',
    date: '2026-07-13',
    variantLabel: 'Preto, Azul',
    details: [
      ['Conforto', 'achei bem gostoso'],
      ['Estilo', 'moderno'],
      ['Material', 'material bom'],
    ],
  }),

  // Boné Flávio Bolsonaro (enviadas pelo vendedor em 26/09/2026)
  boneFlavio({
    author: 'u*****7',
    date: '2026-09-05',
    photo: '/avaliacoes/bone-flavio-1.webp',
    variantLabel: 'Preto',
    details: [['Custo-benefício', 'muito muito muito bom vou comprar mais um de cada cor aqui é 22']],
    helpful: 1,
  }),
  boneFlavio({
    author: 'a*****6',
    date: '2026-09-07',
    photo: '/avaliacoes/bone-flavio-2.webp',
    variantLabel: 'Preto',
    details: [
      ['Visual sugerido', 'amei o none'],
      ['Ocasião adequada', 'politica'],
      ['Adequado', 'sim'],
    ],
    text: 'Amei demais',
    helpful: 7,
  }),
  boneFlavio({
    author: 'o*****3',
    date: '2026-09-02',
    variantLabel: 'Amarelo',
    details: [
      ['Visual sugerido', 'muito bom'],
      ['Estilo', 'muito bonito'],
      ['Custo-benefício', 'ótimo'],
    ],
    helpful: 6,
  }),
  boneFlavio({
    author: 'y*****p',
    date: '2026-09-09',
    variantLabel: 'Amarelo',
    details: [
      ['Qualidade', 'bom'],
      ['Estilo', 'legal'],
    ],
    text: 'Chegou rapidinho',
    helpful: 2,
  }),
  boneFlavio({
    author: 'b*****6',
    date: '2026-09-04',
    variantLabel: 'Verde',
    text: 'Chegou super rápido ótima qualidade',
    helpful: 2,
  }),
  boneFlavio({
    author: 'm*****1',
    date: '2026-09-04',
    variantLabel: 'Amarelo',
    details: [['Custo-benefício', 'chegou bem embalado, boa qualidade, gostei']],
  }),
  boneFlavio({
    author: 'c*****a',
    date: '2026-09-11',
    variantLabel: 'Verde',
    details: [['Conforto', 'o bone e muito confortável, vou usar ate a eleição']],
    helpful: 1,
  }),
  boneFlavio({
    author: 'j*****0',
    date: '2026-09-01',
    variantLabel: 'Amarelo',
    details: [
      ['Ocasião adequada', 'perfect'],
      ['Adequado', 'sim'],
      ['Estilo', 'bom'],
    ],
    helpful: 1,
  }),
  boneFlavio({
    author: 's*****1',
    date: '2026-09-12',
    variantLabel: 'Verde',
    details: [['Conforto', 'top produto']],
    helpful: 1,
  }),
  boneFlavio({
    author: 'v*****1',
    date: '2026-09-04',
    variantLabel: 'Amarelo',
    details: [
      ['Custo-benefício', 'ggostei'],
      ['Adequado', 'tamanho exato'],
    ],
    helpful: 2,
  }),
  boneFlavio({
    author: '3*****i',
    date: '2026-08-28',
    variantLabel: 'Amarelo',
    text: 'Comprei do Flávio Bolsonaro e me mandou escrito Brasil 🫪🫪🫪',
    helpful: 4,
  }),
  boneFlavio({
    author: 'c*****6',
    date: '2026-09-05',
    variantLabel: 'Azul',
    details: [['Ocasião adequada', 'não recomendo não veio conforme o anúncio']],
  }),
  boneFlavio({
    author: 't*****r',
    date: '2026-09-10',
    variantLabel: 'Amarelo',
    details: [
      ['Qualidade', 'material bom e confortável'],
      ['Estilo', 'modelo tradicional'],
      ['Cor', 'Escolhi amarelo, mas veio preto'],
    ],
    helpful: 6,
  }),
  boneFlavio({
    author: 'j*****0',
    date: '2026-09-04',
    variantLabel: 'Preto',
    details: [
      ['Custo-benefício', 'bom'],
      ['Adequado', 'bom'],
      ['Estilo', 'casual'],
    ],
    text: 'Confortável',
    helpful: 5,
  }),

  // Boné Camuflado (enviadas pelo vendedor em 26/09/2026)
  boneCamuflado({
    author: 'f*****a',
    date: '2026-01-13',
    photo: '/avaliacoes/bone-camuflado-1.webp',
    variantLabel: 'Bege',
    details: [['Adequado', 'tamanho ideal,material resistente ótimo custo benefício']],
    helpful: 16,
  }),
  boneCamuflado({
    author: 'i*****5',
    date: '2025-12-02',
    photo: '/avaliacoes/bone-camuflado-2.webp',
    variantLabel: 'Bege',
    text: 'Eu já tinha comprado um preto e vi que o boné era extremamente de qualidade resolvi comprar esse outro ,veio super bem embalado, chegou antes do prazo, vendedor me deu toda atenção,responde rápido no chat, parabéns vendedor e entregador 👏🏻👏🏻, continuarei comprando nessa loja.',
    helpful: 21,
  }),
  boneCamuflado({
    author: 'c*****3',
    date: '2026-05-16',
    photo: '/avaliacoes/bone-camuflado-3.webp',
    variantLabel: 'Azul Marinho, Preto, Verde Camuflado',
    details: [
      ['Tecido', 'achei o material otimo'],
      ['Acabamento', 'o acabamento é top'],
      ['Modelo', 'o modelo é visual e do brasil'],
    ],
    text: 'Muito bom o matéria super recomendo bom de mais ,pode compra que não vão se arrepender.',
    helpful: 4,
  }),
  boneCamuflado({
    author: 'f*****p',
    date: '2026-05-04',
    photo: '/avaliacoes/bone-camuflado-4.webp',
    variantLabel: 'Preto',
    details: [['Tecido', 'bom']],
    text: 'Na medida, gostei de verdade.\nChegou antes do prazo.',
    helpful: 3,
  }),
  boneCamuflado({
    author: 'm*****s',
    date: '2026-08-22',
    photo: '/avaliacoes/bone-camuflado-5.webp',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'material forte'],
      ['Modelo', 'gostei do material. chegou no plazo e bem embalado'],
    ],
  }),
  boneCamuflado({
    author: 'f*****n',
    date: '2026-06-18',
    photo: '/avaliacoes/bone-camuflado-6.webp',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'tecido excelente, muito bom o material.'],
      ['Acabamento', 'ótimo acabamento'],
      ['Modelo', 'modelo militar'],
    ],
    text: 'Gostei muito,uso no meu trabalho, valeu',
    helpful: 1,
  }),
  boneCamuflado({
    author: 'r*****l',
    date: '2026-04-15',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'ótimo'],
      ['Acabamento', 'top'],
      ['Modelo', 'muito bonito'],
    ],
    text: 'O material do boné é muito bom bem acabado costuras fortes e a linha do bordado é muito bonito',
    helpful: 6,
  }),
  boneCamuflado({
    author: 's*****_',
    date: '2026-06-27',
    variantLabel: 'Cinza',
    details: [
      ['Tecido', 'Otimo matetirial, bandeira bordada .'],
      ['Acabamento', 'otimo acabamento .'],
      ['Modelo', 'Modelos simples , basico e elegante .'],
    ],
    text: 'Excelente , já tenho um preto e um bege . Agora são 4 ao todo .',
    helpful: 2,
  }),
  boneCamuflado({
    author: 'e*****l',
    date: '2026-06-23',
    variantLabel: 'Azul Marinho',
    text: 'Ótima qualidade\nJá comprei 3\nEsse veio de marca diferente, mas não deixa de ter qualidade',
  }),
  boneCamuflado({
    author: 's*****i',
    date: '2026-06-20',
    variantLabel: 'Preto, Bege',
    details: [
      ['Tecido', 'ótimo'],
      ['Acabamento', 'nota 10'],
      ['Modelo', 'fica bem na cabeça, modelo ok'],
    ],
    text: 'Podem comprar sem medo.',
  }),
  boneCamuflado({
    author: 'a*****s',
    date: '2026-07-05',
    variantLabel: 'Bege',
    details: [
      ['Custo-benefício', 'excelente'],
      ['Adequado', 'tamanho certinho'],
      ['Visual sugerido', 'Bermuda'],
    ],
    text: 'Muito top o chapéu.\nA qualidade é ótima, muito bem feito!!\nO bordado maravilhoso! Super recomendo.\nVendedor excelente, comprem sem medo, qualidade excelente.',
    helpful: 1,
  }),
  boneCamuflado({
    author: 'l*****1',
    date: '2026-08-25',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'boa qualidade'],
      ['Acabamento', 'bom'],
      ['Modelo', 'todos os modelos'],
    ],
    text: 'Produto de ótima qualidade.',
  }),
  boneCamuflado({
    author: 's*****2',
    date: '2026-05-20',
    variantLabel: 'Preto',
    text: 'Chegou muito rápido. O boné tem material de qualidade e é muito bonito. O bordado é bem feito. Eu amei! Obrigada vendedor 🫶🏾',
    helpful: 3,
  }),
  boneCamuflado({
    author: 's*****a',
    date: '2026-08-15',
    variantLabel: 'Cinza',
    details: [
      ['Tecido', 'forte'],
      ['Acabamento', 'ótimo'],
      ['Modelo', 'moderno'],
    ],
    text: 'É lindo, ótimo, tecido bom e forte, meu esposo gostou muito,e pretende comprar outras cores, e a entrega foi dentro do prazo',
  }),
  boneCamuflado({
    author: 'z*****u',
    date: '2026-01-04',
    variantLabel: 'Verde',
    text: 'Olá, recebi o pedido no prazo estabelecido pelo o vendedor, bem embalado e sem defeitos, gostei muito do boné, bem costurado, confortável, veio na cor que pedi, recomendo a todos que gostam de bonés.Obrigado!',
    helpful: 4,
  }),
  boneCamuflado({
    author: 'd*****s',
    date: '2026-06-30',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'muito bom. Me surpreendi'],
      ['Acabamento', 'excelente acabamento'],
      ['Modelo', 'modelo identico ao anuncio.'],
    ],
    text: 'Com certeza vou comprar outros',
    helpful: 1,
  }),
  boneCamuflado({
    author: 'e*****o',
    date: '2026-07-04',
    variantLabel: 'Verde',
    details: [
      ['Tecido', 'bom'],
      ['Acabamento', 'otimo'],
      ['Modelo', 'modelo versátil e neutro, combina com muitos estilos'],
    ],
    text: 'Comprei para o meu marido e ele amou',
  }),
  boneCamuflado({
    author: 'a*****n',
    date: '2026-04-03',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'tecido forte e cor forte'],
      ['Acabamento', 'boa costura e acabamento caprichado'],
      ['Modelo', 'o modelo combina com as roupas que utilizo para treinar e até uma saída casual.'],
    ],
    helpful: 3,
  }),
  boneCamuflado({
    author: 'e*****1',
    date: '2026-06-05',
    variantLabel: 'Verde',
    text: 'O boné é de boa qualidade,preço baixo.Comprei outros do mesmo vendedor.',
    helpful: 2,
  }),
  boneCamuflado({
    author: 'c*****4',
    date: '2026-06-30',
    variantLabel: 'Verde',
    details: [
      ['Tecido', 'tecido encorpado'],
      ['Acabamento', 'muito bom'],
      ['Modelo', 'lindo e o verde musgo é muito discreto.'],
    ],
  }),
  boneCamuflado({
    author: '0*****v',
    date: '2025-11-11',
    variantLabel: 'Verde Camuflado',
    details: [
      ['Estilo', 'Militar'],
      ['Adequado', 'Muito bom produto'],
      ['Ocasião adequada', 'Estamos bem satisfeitos'],
    ],
    text: 'Excelente compra, entrega rápida e segura, estamos satisfeitos com a compra, muito bom produto.🙏🙏🙏',
    helpful: 8,
  }),
  boneCamuflado({
    author: 'f*****f',
    date: '2026-01-10',
    variantLabel: 'Bege',
    text: 'Excelente produto, chegou no prazo, bem embalado, muito bonito e de excelente qualidade. Altamente recomendado.',
    helpful: 1,
  }),
  boneCamuflado({
    author: 'l*****o',
    date: '2026-07-10',
    variantLabel: 'Verde, Preto, Verde Camuflado',
    details: [
      ['Tecido', 'super resistente'],
      ['Acabamento', 'costuras super resistentes'],
      ['Modelo', 'o modelo militar combina com tudo, recomendo super.'],
    ],
  }),
  boneCamuflado({
    author: 'a*****1',
    date: '2026-08-23',
    variantLabel: 'Preto',
    details: [
      ['Tecido', 'material muito bom. Recomendo'],
      ['Acabamento', 'Acabamento bem feito costura boa'],
      ['Modelo', 'modelo bonito e bem ajustável a cabeça.'],
    ],
  }),

  // Boné Número 13 (enviadas pelo vendedor em 26/09/2026; duas vieram repetidas na lista e entraram uma vez)
  boneNumero13({
    author: 'a*****f',
    date: '2026-09-09',
    photo: '/avaliacoes/bone-numero-13-1.webp',
    variantLabel: 'Vermelho',
    text: 'Super recomendo material muito bom super resistente',
    helpful: 3,
  }),
  boneNumero13({ author: 'm*****9', date: '2026-09-08', photo: '/avaliacoes/bone-numero-13-2.webp', variantLabel: 'Preto', helpful: 4 }),
  boneNumero13({
    author: 'p*****b',
    date: '2026-09-25',
    photo: '/avaliacoes/bone-numero-13-3.webp',
    variantLabel: 'Vermelho',
    details: [['Adequado', 'ideal']],
    text: 'Excelente, chegou antes do prazo e material ideal',
  }),
  boneNumero13({
    author: 'e*****i',
    date: '2026-09-24',
    photo: '/avaliacoes/bone-numero-13-4.webp',
    variantLabel: 'Vermelho',
    details: [['Ocasião adequada', 'chegou super rápido, muito bem feito o boné e será muito 7sado']],
    helpful: 1,
  }),
  boneNumero13({
    author: 'j*****0',
    date: '2026-09-24',
    photo: '/avaliacoes/bone-numero-13-5.webp',
    variantLabel: 'Vermelho',
    details: [
      ['Ocasião adequada', 'eleição'],
      ['Adequado', 'política'],
      ['Custo-benefício', 'bom'],
    ],
    text: 'Chegou no prazo bem embado',
  }),
  boneNumero13({
    author: 'j*****a',
    date: '2026-09-23',
    variantLabel: 'Vermelho',
    text: 'O boné é de um material muito bom e o vermelho é bem vibrante... Recomendo com certeza. 🇧🇷1️⃣3️⃣',
  }),
  boneNumero13({
    author: 'c*****0',
    date: '2026-09-16',
    variantLabel: 'Vermelho',
    details: [
      ['Custo-benefício', 'material maravilhoso'],
      ['Estilo', 'resistente'],
    ],
    helpful: 4,
  }),
  boneNumero13({
    author: 'm*****2',
    date: '2026-09-16',
    variantLabel: 'Preto',
    details: [
      ['Custo-benefício', 'gostei'],
      ['Visual sugerido', 'bem acabado'],
      ['Adequado', 'sim'],
    ],
    helpful: 2,
  }),
  boneNumero13({ author: 'k*****5', date: '2026-09-26', variantLabel: 'Preto', text: 'Chegou conforme o anúncio' }),
  boneNumero13({ author: 'v*****6', date: '2026-09-26', variantLabel: 'Vermelho', text: 'Lindíssimo jente maravilhoso' }),
  boneNumero13({ author: 'r*****e', date: '2026-09-22', variantLabel: 'Preto', text: 'Chegou muito rápido,ameiii', helpful: 1 }),
  boneNumero13({ author: 'd*****l', date: '2026-09-18', variantLabel: 'Vermelho', details: [['Visual sugerido', 'adorei']], helpful: 1 }),
  boneNumero13({ author: 's*****o', date: '2026-09-17', variantLabel: 'Vermelho', helpful: 1 }),
  boneNumero13({ author: 'l*****n', date: '2026-09-13', variantLabel: 'Preto', text: 'Bom' }),
  boneNumero13({ author: 's*****a', date: '2026-09-15', variantLabel: 'Vermelho', helpful: 3 }),
  boneNumero13({ author: 'u*****5', date: '2026-09-24', variantLabel: 'Vermelho' }),
  boneNumero13({ author: 't*****9', date: '2026-09-24', variantLabel: 'Vermelho' }),
  boneNumero13({ author: '7*****l', date: '2026-09-23', variantLabel: 'Vermelho' }),
  boneNumero13({ author: 'm*****1', date: '2026-09-10', variantLabel: 'Preto' }),
  boneNumero13({ author: 's*****s', date: '2026-09-09', variantLabel: 'Preto' }),
  boneNumero13({ author: 'c*****u', date: '2026-09-21', variantLabel: 'Preto' }),
  boneNumero13({ author: 'c*****_', date: '2026-09-06', variantLabel: 'Vermelho' }),

  // Boné Simples: as mesmas avaliações nos dois lados (pedido do vendedor)
  ...[...boneSimples, ...lulaSeis, ...exTruckerLiso].map(daShopee('13', 'simples')),
  ...[...boneSimples, ...lulaSeis, ...exTruckerLiso].map(daShopee('22', 'simples')),

  // Boné Lula (estrela) (enviadas pelo vendedor em 26/09/2026)
  boneLulaEstrela({
    author: '6*****o',
    date: '2026-09-09',
    photo: '/avaliacoes/bone-lula-estrela-1.png',
    variantLabel: 'Vermelho',
    details: [
      ['Estilo', 'Estilo formal.'],
      ['Adequado', 'Vou usar em Camoanha'],
      ['Custo-benefício', 'Igual ao anúncio.Confortavel.'],
    ],
    text: 'Chegou rápido.Gostei da minha compra',
    helpful: 5,
  }),
  boneLulaEstrela({
    author: 'n*****0',
    date: '2026-09-05',
    photo: '/avaliacoes/bone-lula-estrela-2.webp',
    variantLabel: 'Vermelho',
    details: [
      ['Estilo', 'muito bom, excelente'],
      ['Ocasião adequada', 'dar pra o dia a dia'],
      ['Adequado', 'tamanho excelente'],
    ],
    helpful: 7,
  }),
  boneLulaEstrela({
    author: 's*****o',
    date: '2026-08-30',
    photo: '/avaliacoes/bone-lula-estrela-3.webp',
    variantLabel: 'Vermelho',
    details: [
      ['Estilo', 'o modelo é maravilhoso'],
      ['Visual sugerido', 'cor muito boa também'],
    ],
    text: 'Pode comprar sem medo o material é muito bom chega antes do prazo',
    helpful: 6,
  }),
  boneLulaEstrela({ author: 's*****k', date: '2026-09-06', photo: '/avaliacoes/bone-lula-estrela-4.webp', variantLabel: 'Preto', text: 'Muito bom material, chego mais rápido que previsto, amei' }),
  boneLulaEstrela({
    author: 'e*****o',
    date: '2026-09-07',
    photo: '/avaliacoes/bone-lula-estrela-5.webp',
    variantLabel: 'Vermelho',
    details: [['Custo-benefício', 'ótimo boné gostei vou usar no dia da eleição.']],
  }),
  boneLulaEstrela({ author: 'v*****y', date: '2026-09-05', variantLabel: 'Vermelho', details: [['Adequado', 'ameii']] }),
  boneLulaEstrela({ author: 'l*****o', date: '2026-09-26', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'w*****v', date: '2026-09-26', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'g*****8', date: '2026-09-26', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'p*****c', date: '2026-09-06', variantLabel: 'Vermelho', helpful: 4 }),
  boneLulaEstrela({ author: 'w*****y', date: '2026-09-18', variantLabel: 'Vermelho', text: 'Lula presidente!!' }),
  boneLulaEstrela({ author: 'm*****a', date: '2026-09-24', variantLabel: 'Vermelho', text: 'Chegou em perfeito estado, a arte muito bem feita' }),
  boneLulaEstrela({
    author: 'a*****2',
    date: '2026-09-15',
    variantLabel: 'Vermelho',
    details: [
      ['Conforto', 'ótimo'],
      ['Formato', 'sim'],
      ['Estilo', 'ótimo'],
    ],
  }),
  boneLulaEstrela({ author: 'l*****3', date: '2026-09-18', variantLabel: 'Vermelho', details: [['Conforto', 'bom bonito']], helpful: 1 }),
  boneLulaEstrela({ author: 'v*****a', date: '2026-09-12', variantLabel: 'Vermelho', helpful: 1 }),
  boneLulaEstrela({ author: 'e*****3', date: '2026-09-17', variantLabel: 'Vermelho', helpful: 2 }),
  boneLulaEstrela({
    author: 'n*****2',
    date: '2026-09-19',
    variantLabel: 'Vermelho',
    details: [
      ['Conforto', 'bom'],
      ['Formato', 'só amassado um pouco'],
    ],
  }),
  boneLulaEstrela({ author: 'f*****r', date: '2026-09-14', variantLabel: 'Vermelho', text: 'Gostei!' }),
  boneLulaEstrela({ author: 'd*****l', date: '2026-09-15', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'r*****9', date: '2026-09-19', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'n*****2', date: '2026-09-22', variantLabel: 'Vermelho', details: [['Estilo', 'é lindo eu ameii']] }),
  boneLulaEstrela({ author: 'm*****a', date: '2026-09-12', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'm*****o', date: '2026-09-22', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: '5*****y', date: '2026-09-12', variantLabel: 'Branco com preto' }),
  boneLulaEstrela({ author: '5*****y', date: '2026-09-12', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'm*****3', date: '2026-08-31', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 't*****s', date: '2026-09-19', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'j*****9', date: '2026-09-12', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'r*****0', date: '2026-09-23', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'f*****r', date: '2026-09-24', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'e*****3', date: '2026-09-26', variantLabel: 'Preto' }),
  boneLulaEstrela({ author: 'v*****8', date: '2026-08-29', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'f*****1', date: '2026-09-14', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: '0*****t', date: '2026-09-10', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'j*****s', date: '2026-09-11', variantLabel: 'Vermelho' }),
  boneLulaEstrela({ author: 'n*****p', date: '2026-09-22', variantLabel: 'Vermelho' }),

  // Boné Lula (letras grandes) (enviadas pelo vendedor em 26/09/2026)
  // Fotos só nesta página (a lista lulaSeis também aparece no Trucker liso, que é liso).
  // O vendedor enviou a mesma foto como 1ª e 5ª.
  ...lulaSeis.map((r, i) => {
    const foto = ['1', '2', '3', '4', '1'][i]
    return boneLulaLetras(foto ? { ...r, photo: `/avaliacoes/bone-lula-letras-${foto}.webp` } : r)
  }),
  boneLulaLetras({ author: 'e*****p', date: '2026-09-22', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'j*****x', date: '2026-09-18', variantLabel: 'Preto' }),
  boneLulaLetras({ author: 'r*****a', date: '2026-09-21', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'j*****9', date: '2026-09-01', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'c*****o', date: '2026-09-05', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'a*****s', date: '2026-09-06', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'm*****5', date: '2026-09-07', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'j*****l', date: '2026-09-08', variantLabel: 'Vermelho' }),
  boneLulaLetras({ author: 'r*****2', date: '2026-09-08', variantLabel: 'Branco' }),
]
